### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kasperskybest** [Frontmancoder/Nitrogen#1]
 npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/Nitrogen/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/Nitrogen/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-07T14_16_39_013Z-debug.log
exit status 254


**Comment by Frontmancoder** [comment]
Ok i see
someone else also got
let me try
